<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Anshuls-MacBook-Air.local" ignored="0" name="Listener Test Case" tests="5" failures="1" timestamp="05 Jan 2019 15:02:25 GMT" time="0.187" errors="0">
  <testcase name="testFour" time="0.022" classname="com.testng.listeners.SampleTestClass">
    <skipped/>
  </testcase> <!-- testFour -->
  <testcase name="testGetData" time="0.004" classname="com.testng.listeners.SampleTestClass"/>
  <testcase name="testGetData" time="0.005" classname="com.testng.listeners.SampleTestClass"/>
  <testcase name="testOne" time="0.009" classname="com.testng.listeners.SampleTestClass"/>
  <testcase name="testThree" time="0.015" classname="com.testng.listeners.SampleTestClass">
    <failure type="java.lang.AssertionError" message="expected [7] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [7] but found [5]
at com.testng.listeners.SampleTestClass.testThree(SampleTestClass.java:26)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testThree -->
</testsuite> <!-- Listener Test Case -->
